[package]
name = "adi0nt/fluent-renewed-plus"
version = "1.0.1"
license = "MIT"
authors = ["Adi0nt"]
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/Adi0nt/fluent-renewed-plus"
realm = "shared"

[dependencies]
Signal = "nowoshire/namedsignal@1.2.1"
Flipper = "reselim/flipper@2.0.0"